name: HCL Custom Scan

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to scan'
        required: true
        default: 'https://github.com/HabanaAI/HCL'
      rate-limit:
        description: 'Rate limit GitHub API requests'
        required: false
        default: 150
        type: number

jobs:
  hcl-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SRS Repository
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang clang-tidy infer
      
      - name: Build HCL Project
        run: |
          cd /home/root123/gaudi/srs/HCL/hcl/src
          export HCL_SRC_PKG_DIR=/home/root123/gaudi/HCL
          export HCL_LIB_DIR=/home/root123/gaudi/HCL/hcl/include  # Updated HCL_LIB_DIR to point to include directory
          cmake -DCMAKE_CXX_FLAGS="-I${HCL_LIB_DIR}" .
          make
        continue-on-error: true
      
      - name: Run clang scan-build
        run: |
          scan-build -o ./clang-results --status-bugs make -C /home/root123/gaudi/HCL/hcl/src
        continue-on-error: true

      - name: Run clang-tidy
        run: |
          clang-tidy /home/root123/gaudi/HCL/hcl/src/*.cpp -- -I /home/root123/gaudi/HCL/hcl/include
        continue-on-error: true

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.json
        continue-on-error: true

      - name: Run Infer Static Analysis
        run: |
          infer run -- make -C /home/root123/gaudi/HCL/hcl/src
        continue-on-error: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hcl-scan-results
          path: |
            ./clang-results
            ./results.json
            ./infer-out

